# Generated by Django 5.0.14 on 2025-06-03 02:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0002_alter_asset_asset_type_alter_asset_metadata_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIGenerationTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_image_url_for_ai",
                    models.URLField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="提交给AI的源图片URL",
                    ),
                ),
                (
                    "text_prompt",
                    models.TextField(blank=True, null=True, verbose_name="文本提示"),
                ),
                (
                    "meshy_task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Meshy任务ID",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Celery任务ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待处理"),
                            ("IN_PROGRESS", "处理中"),
                            ("SUCCEEDED", "成功"),
                            ("FAILED", "失败"),
                            ("CELERY_RECEIVED", "Celery任务已接收"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度")),
                (
                    "meshy_result_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Meshy API结果",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "generated_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_source_task",
                        to="main.asset",
                        verbose_name="生成的资产",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI生成任务",
                "verbose_name_plural": "AI生成任务",
                "ordering": ["-created_at"],
            },
        ),
    ]
