# Generated by Django 5.0.14 on 2025-06-03 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_generator", "0001_initial"),
        ("main", "0003_asset_ai_model_used_asset_external_ai_task_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aigenerationtask",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "AI生成任务记录",
                "verbose_name_plural": "AI生成任务记录",
            },
        ),
        migrations.RemoveField(
            model_name="aigenerationtask",
            name="meshy_task_id",
        ),
        migrations.AddField(
            model_name="aigenerationtask",
            name="external_ai_preview_task_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="外部AI预览任务ID (用于文生3D两阶段)",
            ),
        ),
        migrations.AddField(
            model_name="aigenerationtask",
            name="external_ai_service_name",
            field=models.CharField(
                default="MeshyAI", max_length=50, verbose_name="外部AI服务名称"
            ),
        ),
        migrations.AddField(
            model_name="aigenerationtask",
            name="external_ai_task_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="外部AI任务ID (例如Meshy的任务ID)",
            ),
        ),
        migrations.AddField(
            model_name="aigenerationtask",
            name="generation_params",
            field=models.JSONField(blank=True, default=dict, verbose_name="AI生成参数"),
        ),
        migrations.AddField(
            model_name="aigenerationtask",
            name="source_image_urls_for_ai",
            field=models.JSONField(
                blank=True, default=list, verbose_name="提交给AI的多张源图片URL列表"
            ),
        ),
        migrations.AddField(
            model_name="aigenerationtask",
            name="target_asset_for_texture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_texture_generation_tasks",
                to="main.asset",
                verbose_name="纹理目标资产 (如果是生成纹理)",
            ),
        ),
        migrations.AddField(
            model_name="aigenerationtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("IMG_TO_3D", "图像生成3D"),
                    ("TXT_TO_3D_PRE", "文本生成3D预览"),
                    ("TXT_TO_3D_REF", "文本生成3D精细化"),
                    ("MULTI_IMG_3D", "AI多图生成3D"),
                    ("TXT_TO_TEX", "AI文本生成纹理"),
                ],
                default="IMG_TO_3D",
                max_length=20,
                verbose_name="AI任务类型",
            ),
        ),
        migrations.AlterField(
            model_name="aigenerationtask",
            name="generated_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_source_task",
                to="main.asset",
                verbose_name="生成的资产 (如果是模型)",
            ),
        ),
        migrations.AlterField(
            model_name="aigenerationtask",
            name="meshy_result_data",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Meshy API原始结果"
            ),
        ),
        migrations.AlterField(
            model_name="aigenerationtask",
            name="progress",
            field=models.IntegerField(default=0, verbose_name="进度 (%)"),
        ),
        migrations.AlterField(
            model_name="aigenerationtask",
            name="source_image_url_for_ai",
            field=models.URLField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="提交给AI的单张源图片URL",
            ),
        ),
        migrations.AlterField(
            model_name="aigenerationtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "等待处理"),
                    ("CELERY_RECEIVED", "Celery任务已接收"),
                    ("AI_API_PENDING", "AI API处理中"),
                    ("AI_API_PREVIEW_SUCCEEDED", "AI API预览成功"),
                    ("AI_API_REFINING", "AI API精细化中"),
                    ("AI_API_SUCCEEDED", "AI API处理成功"),
                    ("DOWNLOADING_ASSET", "下载AI生成资产中"),
                    ("UPLOADING_TO_OSS", "上传至OSS中"),
                    ("CREATING_ASSET_RECORD", "创建资产记录中"),
                    ("TRIGGERING_THUMBNAIL", "触发缩略图生成中"),
                    ("COMPLETED", "完成"),
                    ("FAILED", "失败"),
                ],
                default="PENDING",
                max_length=30,
                verbose_name="任务状态",
            ),
        ),
        migrations.AlterField(
            model_name="aigenerationtask",
            name="text_prompt",
            field=models.TextField(
                blank=True, null=True, verbose_name="文本提示 (用于文生3D或文生纹理)"
            ),
        ),
        migrations.AlterField(
            model_name="aigenerationtask",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_generation_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
