# Generated by Django 5.0.14 on 2025-07-02 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_generator", "0003_chatsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="aigenerationtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("IMG_TO_3D", "图像生成3D"),
                    ("TXT_TO_3D_PRE", "文本生成3D预览"),
                    ("TXT_TO_3D_REF", "文本生成3D精细化"),
                    ("MULTI_IMG_3D", "AI多图生成3D"),
                    ("TXT_TO_TEX", "AI文本生成纹理"),
                    ("DECOR_PLAN", "家装方案生成"),
                ],
                default="IMG_TO_3D",
                max_length=20,
                verbose_name="AI任务类型",
            ),
        ),
        migrations.CreateModel(
            name="DecorPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="方案标题")),
                (
                    "final_pdf_url",
                    models.URLField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="方案PDF文件URL",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "source_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_decor_plan",
                        to="ai_generator.aigenerationtask",
                        verbose_name="来源AI任务",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decor_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI家装方案",
                "verbose_name_plural": "AI家装方案",
                "ordering": ["-created_at"],
            },
        ),
    ]
