# Generated by Django 5.0.14 on 2025-07-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_generator", "0004_alter_aigenerationtask_task_type_decorplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="decorplan",
            name="generated_image_urls",
            field=models.JSONField(
                blank=True, default=list, verbose_name="生成的效果图URL"
            ),
        ),
        migrations.AddField(
            model_name="decorplan",
            name="generated_text_content",
            field=models.JSONField(
                blank=True, default=list, verbose_name="生成的文本内容"
            ),
        ),
    ]
