# Generated by Django 5.0.14 on 2025-05-22 02:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="材质名称")),
                (
                    "texture_map_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="漫反射纹理图URL",
                    ),
                ),
                (
                    "normal_map_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="法线贴图URL",
                    ),
                ),
                (
                    "roughness_map_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="粗糙度贴图URL",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("wood", "木材"),
                            ("metal", "金属"),
                            ("fabric", "织物"),
                            ("glass", "玻璃"),
                            ("other", "其他"),
                        ],
                        max_length=100,
                        verbose_name="材质类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "材质",
                "verbose_name_plural": "材质",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="资产名称")),
                ("description", models.TextField(blank=True, verbose_name="资产描述")),
                (
                    "file_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="3D模型文件URL",
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="缩略图URL"
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("furniture", "家具"),
                            ("architectural_style", "建筑风格"),
                            ("material", "材质"),
                            ("lighting", "灯光"),
                        ],
                        max_length=50,
                        verbose_name="资产类型",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="额外元数据"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产",
                "verbose_name_plural": "资产",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, verbose_name="项目描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="项目所有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "设计项目",
                "verbose_name_plural": "设计项目",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="房间名称")),
                (
                    "dimensions",
                    models.JSONField(default=dict, verbose_name="房间尺寸 (长宽高)"),
                ),
                (
                    "room_type",
                    models.CharField(
                        help_text="例如: 客厅, 卧室, 厨房",
                        max_length=100,
                        verbose_name="房间类型",
                    ),
                ),
                (
                    "design_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="main.designproject",
                        verbose_name="所属设计项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "房间",
                "verbose_name_plural": "房间",
                "unique_together": {("design_project", "name")},
            },
        ),
        migrations.CreateModel(
            name="DesignLayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.JSONField(default=dict, verbose_name="位置 (x,y,z)"),
                ),
                (
                    "rotation",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="旋转 (四元数或欧拉角)"
                    ),
                ),
                ("scale", models.JSONField(default=dict, verbose_name="缩放 (x,y,z)")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layouts",
                        to="main.asset",
                        verbose_name="放置资产",
                    ),
                ),
                (
                    "material_override",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.material",
                        verbose_name="材质覆盖",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layouts",
                        to="main.room",
                        verbose_name="所属房间",
                    ),
                ),
            ],
            options={
                "verbose_name": "设计布局",
                "verbose_name_plural": "设计布局",
                "ordering": ["room", "asset"],
            },
        ),
        migrations.CreateModel(
            name="DesignBackpack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_backpacks",
                        to="main.asset",
                        verbose_name="收藏资产",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_backpack_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "设计背包",
                "verbose_name_plural": "设计背包",
                "ordering": ["-added_at"],
                "unique_together": {("user", "asset")},
            },
        ),
    ]
