# Generated by Django 5.0.14 on 2025-05-27 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("FURNITURE", "家具"),
                    ("MATERIAL", "材质"),
                    ("LIGHTING", "灯光"),
                    ("ARCH_STYLE", "建筑风格"),
                    ("IMAGE", "图片"),
                    ("MODEL_3D", "3D模型"),
                    ("OTHER", "其他"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="资产类型",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="metadata",
            field=models.JSONField(blank=True, null=True, verbose_name="元数据"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="上传用户",
            ),
        ),
    ]
