# Generated by Django 5.0.14 on 2025-06-03 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_asset_asset_type_alter_asset_metadata_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="ai_model_used",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="使用的AI模型"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="external_ai_task_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="外部AI任务ID",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="source_reference_input",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="来源参考输入"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("UPLOADED", "用户上传"),
                    ("AI_TXT_3D", "AI文本生成3D"),
                    ("AI_IMG_3D", "AI单图生成3D"),
                    ("AI_MULTI_IMG_3D", "AI多图生成3D"),
                ],
                default="UPLOADED",
                max_length=20,
                verbose_name="资产来源",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("FURNITURE", "家具"),
                    ("MATERIAL", "材质"),
                    ("LIGHTING", "灯光"),
                    ("ARCH_STYLE", "建筑风格"),
                    ("IMAGE", "图片"),
                    ("MODEL_3D", "3D模型"),
                    ("OTHER", "其他"),
                ],
                default="MODEL_3D",
                max_length=20,
                verbose_name="资产类型",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="file_url",
            field=models.URLField(
                blank=True, max_length=1024, null=True, verbose_name="文件URL"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="元数据"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="thumbnail_url",
            field=models.URLField(
                blank=True, max_length=1024, null=True, verbose_name="缩略图URL"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_assets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="所属用户",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="normal_map_url",
            field=models.URLField(
                blank=True, max_length=1024, null=True, verbose_name="法线贴图URL"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="roughness_map_url",
            field=models.URLField(
                blank=True, max_length=1024, null=True, verbose_name="粗糙度贴图URL"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="texture_map_url",
            field=models.URLField(
                blank=True, max_length=1024, null=True, verbose_name="漫反射纹理图URL"
            ),
        ),
    ]
