# Generated by Django 5.0.14 on 2025-06-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_asset_ai_model_used_asset_external_ai_task_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="designproject",
            name="thumbnail_url",
            field=models.URLField(
                blank=True, max_length=1024, null=True, verbose_name="项目缩略图URL"
            ),
        ),
    ]
