# Generated by Django 5.0.14 on 2025-06-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_designproject_thumbnail_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="dimensions",
        ),
    ]
