# Generated by Django 5.0.14 on 2025-06-24 07:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_room_dimensions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="designlayout",
            options={"verbose_name": "设计布局", "verbose_name_plural": "设计布局"},
        ),
        migrations.RemoveField(
            model_name="designlayout",
            name="material_override",
        ),
        migrations.RemoveField(
            model_name="designlayout",
            name="room",
        ),
        migrations.AlterField(
            model_name="designlayout",
            name="rotation",
            field=models.JSONField(default=dict, verbose_name="旋转 (四元数或欧拉角)"),
        ),
        migrations.CreateModel(
            name="SceneSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="快照名称")),
                (
                    "snapshot_image_url",
                    models.URLField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="快照图片URL",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="main.room",
                        verbose_name="所属房间",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_snapshots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="快照所有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "场景快照",
                "verbose_name_plural": "场景快照",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="designlayout",
            name="scene_snapshot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="layouts",
                to="main.scenesnapshot",
                verbose_name="所属快照",
            ),
        ),
    ]
